# Starship Configuration
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Set 'catppuccin_mocha' as custom color palette
palette = 'catppuccin_mocha'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# A minimal left prompt
format = """$os$username$hostname$directory$git_branch$git_status$git_metrics$fill$cmd_duration$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " 󰌾"
format = "[ $path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](bold fg:green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_metrics]
disabled = false
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[memory_usage]
symbol = "󰍛 "

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[username]
style_user = "bold dimmed blue"
show_always = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = "."
disabled = false

# palette tables should be last in the config ⚓
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
