# Starship configuration optimized for development
format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$nodejs\
$python\
$rust\
$golang\
$java\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[](fg:purple)\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:surface0 fg:text"
disabled = true # Disabled by default

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:green fg:mantle"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:mantle"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:teal fg:mantle"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:teal fg:mantle"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:teal fg:mantle"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:teal fg:mantle"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:teal fg:mantle"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:blue fg:mantle"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:purple fg:mantle"
format = '[ ♥ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

# Catppuccin Mocha color palette
palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
