version: '3.8'

services:
  ubuntu-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu-dev
      args:
        USERNAME: huchen
        USER_UID: 1000
        USER_GID: 1000
    container_name: huchen-dev-env
    hostname: ubuntu-dev
    volumes:
      # Mount workspace
      - ../:/workspace:cached
      # Mount SSH keys (read-only)
      - ~/.ssh:/home/huchen/.ssh:ro
      # Mount git config (read-only)
      - ~/.gitconfig:/home/huchen/.gitconfig:ro
      # Persistent home directory
      - huchen-dev-home:/home/huchen
      # Mount OrbStack socket if available
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # Common development ports
      - "3000:3000"   # React/Next.js
      - "8000:8000"   # Django/FastAPI
      - "8080:8080"   # Spring Boot
      - "5000:5000"   # Flask
      - "4000:4000"   # Jekyll
      - "9000:9000"   # Various services
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
      # Python environment
      - PYTHONPATH=/workspace
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Node.js environment
      - NODE_ENV=development
      # Java environment
      - JAVA_HOME=/home/linuxbrew/.linuxbrew/opt/openjdk@21
    stdin_open: true
    tty: true
    command: zsh
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  ubuntu-dev-home:
    driver: local