# Development overrides for Docker Compose
version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port

  db:
    environment:
      POSTGRES_DB: myapp_dev
    ports:
      - "5433:5432"  # Different port for dev
