# ZSH environment

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export TERM=xterm-256color
export DEFAULT_USER=$USER
export EDITOR='emacsclient -a ""'
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH

# Zinit
export PATH=$HOME/.local/share/zinit/polaris/bin:$PATH

# Cask
export PATH=$HOME/.cask/bin:$PATH

# Golang
export GO111MODULE=auto
export GOPROXY=https://goproxy.io,direct
export GOPATH=$HOME/go
export PATH=${GOPATH//://bin:}/bin:$PATH

# Rust
export PATH=$HOME/.cargo/bin:$PATH

# API Keys - Set these in your environment or ~/.zshrc_local
# export ***REMOVED***=""
# export ***REMOVED***=""
# export GEMINI_API_KEY=""
# export DEEPSEEK_API_KEY=""
# export DEEPSEEK_BASE_URL=""
# export ***REMOVED***=""
# export AVANTE_***REMOVED***=""
# export ***REMOVED***=""
# export ***REMOVED***=""
# setproxy
export https_proxy=http://127.0.0.1:7897 http_proxy=http://127.0.0.1:7897 all_proxy=socks5://127.0.0.1:7897
