version: "3.8"

name: dotfiles-ubuntu24-amd64-dev

networks:
  devnet:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  clickhouse_data:
  clickhouse_logs:

services:
  devbox:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: docker-samples/ubuntu24.04-amd64-dev/Dockerfile
      args:
        USERNAME: ${USER:-huchen}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      USERNAME: ${USER:-huchen}
      # Share host proxy into the container (optional; set on host before up)
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    ports:
      - "21:21"
      - "22:22"
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # Mount your host home; read/write
      - ${HOME}:/host-home
      # Mount host Projects directory into container workspace
      - ${HOME}/Projects:/home/${USER:-huchen}/Projects
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      - postgres
      - redis
      - mongo
      - clickhouse
    networks:
      - devnet

  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devnet

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - devnet

  mongo:
    image: mongo:7
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - devnet

  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    platform: linux/amd64
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    networks:
      - devnet
